### ISSUE TITLE
kraken2simplify.py produces empty files

### ISSUE THREAD

**Issue by lckauer** [sipost1/kraken2OTUtable#2]
Hi, 
I´ve run into an issue using the kraken2simplify.py script. When using the following command, the script produces the right files in the right directory but the files are empty (0Bytes). I do not get an error message or anything.

`python3 kraken2simplify.py /media/ubuntu1/Volume/Kraken2-test/HPL059-1_S55.name.k2report O,F,G`

The k2report files have been created using the --use-names flag (but not the --report-zero-counts flag). Krona visualization and pavian with the report files works totally fine.

Python version I´m using is 3.10.6
Can you tell me what the problem could be?

Thank you in advance.
Regards,
Lea

**Comment by sipost1** [comment]
Hi Lea,
Could you please upload the report file you tried to convert?
I tried to reproduce the issue, but it works for me as it supposed to.

Do you have the permissions set to write on that volume?

**Comment by lckauer** [comment]
Hi,
thanks for the quick reply!
This is the report file i tried to script on. Unfortunately I can not import the file with the .k2report extension so I added .txt to upload it, I hope that doesn´t mess up the file, if so let me know. Sorry I am new to the whole bioinformatics world :)
[HPL059-1_S55.name.k2report.txt](https://github.com/sipost1/kraken2OTUtable/files/11230795/HPL059-1_S55.name.k2report.txt)

Yes I can generate other files on that Volume through commands, I for example generated the .k2report file on that device, if that is what you mean.

**Comment by sipost1** [comment]
Hi,
it seems the report you uploaded is slightly different than the [standard kraken2 report](https://github.com/DerrickWood/kraken2/blob/master/docs/MANUAL.markdown#sample-report-output-format), as it has 8 fields instead of 6. As a quick fix I changed the indexes so it works with this format and pushed the changes to a [new branch](https://github.com/sipost1/kraken2OTUtable/tree/fix_indexing).

I assumed the first three columns are the same as stated in the manual.

Please let me know if you have any further questions.

**Comment by lckauer** [comment]
Hi,
thank you! Now the simplify scripts works just fine!

But as I tried to move on with the concat script, I´ve run into a new error.
This is the code I´ve run:
`python3 kraken2concat.py /media/ubuntu1/Volume/Kraken2-test/All_levels G` 
with "All_levels" being the directory I copied the files produced by the simplify script into.
It gave me the following error:
Traceback (most recent call last):
  File "/media/ubuntu1/Volume/Kraken2-test/kraken2OTUtable-fix_indexing/kraken2concat.py", line 72, in <module>
    read_file_2_dic(i)
  File "/media/ubuntu1/Volume/Kraken2-test/kraken2OTUtable-fix_indexing/kraken2concat.py", line 31, in read_file_2_dic
    with open(f, "r") as source:
FileNotFoundError: [Errno 2] No such file or directory: 'HPL007_S63.name.k2report.G_only.tsv'

I´ve tried with all 3 levels I let the simplify script and it gave the same error. The file for sure is in the directory and if I remove this file the error occurs with another file in the directory and says it can´t find it. 
This is one of the files, generated by the simplify script.
[HPL007_S63.name.k2report.G_only.tsv.txt](https://github.com/sipost1/kraken2OTUtable/files/11247467/HPL007_S63.name.k2report.G_only.tsv.txt)

Thank you again
Lea

**Comment by sipost1** [comment]
Thank you for letting me know about this issue!

The problem was the script was looking for the files in the "current directory" not in the directory the user supplies.
I rewritten the whole thing as originally it was written in a hurry  at the end of my masters just before final exams, so I didn't have enough time to finish it nicely 😄 .

The latest version can be found on main branch.

I would be thankful if you would reply if it works (or not) as intended with "real data" as well, as I only had two files (+ a few derived from this 2) to test it on.

**Comment by lckauer** [comment]
Thank you and sorry for all the inconvenience!

Now it works perfectly fine! :)
